# server配置
server:
  port: 8081

# spring配置
spring:
  # baomidou可以动态切换jdbc数据源
  datasource:
    dynamic:
      # 指定默认数据源
      primary: mysql
      # 严格模式：dao层不指定数据源直接报错,非严格模式允许dao层不配置数据源,会启动默认数据源进行连接
      strict: false
      # 数据源可以不止一个
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/eshop?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
          username: root
          password: Q-D37Sq*k61#yT_y
        ck:
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
          url: jdbc:clickhouse://localhost:8123/ods
          username:
          password:
        hive:
          driver-class-name: org.apache.hive.jdbc.HiveDriver
          url: jdbc:hive2://localhost:10000
          username: hive
          password: 4XUY5mIg1dZlqVp2
        presto:
          driver-class-name: com.facebook.presto.jdbc.PrestoDriver
          url: jdbc:presto://localhost:9000/hive
          username: hadoop
          password:
        hbase:
          driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
          url: jdbc:phoenix:localhost:2181
          username:
          password:
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  # es
  elasticsearch:
    uris: localhost:9200

# mybatis配置
mybatis:
  # settings
  configuration:
    # 日志实现,SLF4J/LOG4J2/STDOUT_LOGGING
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 将下划线映射成驼峰规则
    map-underscore-to-camel-case: true
    # 设置映射范围,NONE/PARTIAL/FULL
    auto-mapping-behavior: full

# 自定义参数,代码中使用@Value("${}")注解引入
data:
  redis:
    key: hotPhone